apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-petclinic-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/22120207/spring-petclinic-microservices-monitoring-helm-chart
    targetRevision: HEAD
    path: spring-petclinic-microservices-monitoring-helm-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true