apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.hostname.alertManager.name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  alertmanager.yml: |-
    global:
      resolve_timeout: 5m

    route:
      receiver: email-alert
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1m

    receivers:
    - name: email-alert
      email_configs:
      - to: "caotienminhktvn3@gmail.com"
        from: "tranngocnhannt2004@gmail.com"
        smarthost: smtp.gmail.com:587
        auth_username: "tranngocnhannt2004@gmail.com"
        auth_password: "{{ env.ALERTMANAGER_PASSWORD }}"
        auth_identity: "tranngocnhannt2004@gmail.com"
        require_tls: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.hostname.alertManager.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.hostname.alertManager.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.hostname.alertManager.name }}
    spec:
      containers:
      - name: {{ .Values.hostname.alertManager.name }}
        image: "{{ .Values.images.alertManager.repository }}:{{ .Values.images.alertManager.tag }}"
        args:
          - "--config.file=/etc/alertmanager/alertmanager.yml"
        ports:
          - containerPort: 9093
        env:
          - name: ALERTMANAGER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.hostname.alertManager.name }}-secret
                key: auth_password
        volumeMounts:
          - name: config-volume
            mountPath: /etc/alertmanager
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.hostname.alertManager.name }}-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.hostname.alertManager.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.hostname.alertManager.name }}
  ports:
    - protocol: TCP
      port: 9093
      targetPort: 9093
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.hostname.alertManager.name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  auth_password: lnci zfby anwh ikyd