apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.hostname.alloyServer.name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  config.alloy: |
    logging {
      level = "info"
      format = "logfmt"
    }
    discovery.kubernetes "pods" {
      role = "pod"
    }
    discovery.relabel "pods" {
      targets = discovery.kubernetes.pods.targets

      rule {
        source_labels = ["__meta_kubernetes_namespace"]
        target_label = "namespace"
        action = "replace"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
        target_label = "app"
        action = "replace"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_container_name"]
        target_label = "container"
        action = "replace"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_name"]
        target_label = "pod"
        action = "replace"
      }
    }
    loki.source.kubernetes "pods" {
      targets    = discovery.relabel.pods.output
      forward_to = [loki.process.process.receiver]
    }
    loki.process "process" {
      forward_to = [loki.write.loki.receiver]

      stage.drop {
        older_than          = "1h"
        drop_counter_reason = "too old"
      }
      stage.match {
        selector = "{app=~\".*\"}"
        stage.json {
          expressions = {
            level = "level",
          }
        }
        stage.labels {
          values = {
            level = "level",
          }
        }
      }
    }
    loki.write "loki" {
      endpoint {
        url = "http://{{ .Values.hostname.lokiServer.name }}:3100/loki/api/v1/push"
      }
    }

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.hostname.alloyServer.name }}-clusterrole
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - services
      - pods
      - pods/log
    verbs:
      - get
      - watch
      - list

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.hostname.alloyServer.name }}-serviceaccount
  namespace: {{ .Values.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.hostname.alloyServer.name }}-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.hostname.alloyServer.name }}-serviceaccount
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.hostname.alloyServer.name }}-clusterrole
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.hostname.alloyServer.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.hostname.alloyServer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.hostname.alloyServer.name }}
    spec:
      serviceAccountName: {{ .Values.hostname.alloyServer.name }}-serviceaccount
      containers:
        - name: {{ .Values.hostname.alloyServer.name }}
          image: "{{ .Values.images.alloyServer.repository }}:{{ .Values.images.alloyServer.tag }}"
          args:
            - run
            - /etc/alloy/config.alloy
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
            - name: varlog
              mountPath: /var/log
            - name: dockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ .Values.hostname.alloyServer.name }}-configmap
        - name: varlog
          hostPath:
            path: /var/log
        - name: dockercontainers
          hostPath:
            path: /var/lib/docker/containers
