apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.hostname.grafanaServer.name }}
  labels:
    app: {{ .Values.hostname.grafanaServer.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.hostname.grafanaServer.name }}
  template:
    metadata:
      name: {{ .Values.hostname.grafanaServer.name }}
      labels:
        app: {{ .Values.hostname.grafanaServer.name }}
    spec:
      containers:
        - name: {{ .Values.hostname.grafanaServer.name }}
          image: "{{ .Values.images.grafanaServer.repository }}:{{ .Values.images.grafanaServer.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: admin-password
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.hostname.grafanaServer.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.hostname.grafanaServer.name }}
  ports:
    - name: {{ .Values.hostname.grafanaServer.name }}-port
      protocol: TCP
      port: 3030
      targetPort: 3000