apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.hostname.grafanaServer.name }}-configmap
  namespace: {{ .Values.namespace }}
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://{{ .Values.hostname.lokiServer.name }}:3100
        isDefault: false

      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://{{ .Values.hostname.prometheusServer.name }}:9091
        isDefault: true

      - name: Zipkin
        type: zipkin
        access: proxy
        url: http://{{ .Values.hostname.tracingServer.name }}:9411
        isDefault: false

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.hostname.grafanaServer.name }}
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ .Values.hostname.grafanaServer.name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.hostname.grafanaServer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.hostname.grafanaServer.name }}
    spec:
      containers:
        - name: {{ .Values.hostname.grafanaServer.name }}
          image: "{{ .Values.images.grafanaServer.repository }}:{{ .Values.images.grafanaServer.tag }}"
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.hostname.grafanaServer.name }}-secret
                  key: admin-password
          volumeMounts:
            - name: {{ .Values.hostname.grafanaServer.name }}-storage
              mountPath: /var/lib/grafanana
            - name: {{ .Values.hostname.grafanaServer.name }}-datasources
              mountPath: /etc/grafana/provisioning/datasources
      volumes:
        - name: {{ .Values.hostname.grafanaServer.name }}-storage
          emptyDir: {}
        - name: {{ .Values.hostname.grafanaServer.name }}-datasources
          configMap:
            name: {{ .Values.hostname.grafanaServer.name }}-configmap
        
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.hostname.grafanaServer.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.hostname.grafanaServer.name }}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.hostname.grafanaServer.name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  admin-password: YWRtaW4=
