apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.hostname.lokiServer.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.hostname.lokiServer.name }}
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.hostname.lokiServer.name }}
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ .Values.hostname.lokiServer.name }}
  selector:
    matchLabels:
      app: {{ .Values.hostname.lokiServer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.hostname.lokiServer.name }}
    spec:
      containers:
        - name: {{ .Values.hostname.lokiServer.name }}
          image: docker.io/grafana/loki:2.9.6
          args:
            - -config.file=/etc/loki/local-config.yaml
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: config-volume
              mountPath: /etc/loki
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.hostname.lokiServer.name }}-configmap

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.hostname.lokiServer.name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  local-config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    common:
      path_prefix: /loki
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    limits_config:
      ingestion_rate_mb: 8
      
      ingestion_burst_size_mb: 16
