apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.hostname.prometheusServer.name }}
  labels:
    app: {{ .Values.hostname.prometheusServer.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.hostname.prometheusServer.name }}
  template:
    metadata:
      name: {{ .Values.hostname.prometheusServer.name }}
      labels:
        app: {{ .Values.hostname.prometheusServer.name }}
    spec:
      containers:
        - name: {{ .Values.hostname.prometheusServer.name }}
          image: "{{ .Values.images.prometheusServer.repository }}:{{ .Values.images.prometheusServer.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.hostname.prometheusServer.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.hostname.prometheusServer.name }}
  ports:
    - name: {{ .Values.hostname.prometheusServer.name }}-port
      protocol: TCP
      port: 9091
      targetPort: 9090